// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customizer': string;
  'customizer-body': string;
  'handle': string;
  'open': string;
}
declare const cssExports: CssExports;
export = cssExports;
