// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'MuiTabs-indicator': string;
  'builder-CustomTabs': string;
  'builder-StyledTab': string;
  'builder-StyledTabs': string;
  'builder-tab-icon': string;
}
declare const cssExports: CssExports;
export = cssExports;
