// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Mui-checked': string;
  'MuiFormControlLabel-label': string;
  'MuiSwitch-switchBase': string;
  'MuiSwitch-track': string;
  'builder-ThemeSwitcher': string;
}
declare const cssExports: CssExports;
export = cssExports;
