// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'builder-Footer': string;
  'builder-Header': string;
  'builder-Main': string;
}
declare const cssExports: CssExports;
export = cssExports;
