// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'builder-LeftCollapse': string;
  'builder-LeftCollapse-content': string;
  'builder-LeftCollapse-content-wrapper': string;
  'builder-LeftCollapse-icon': string;
  'builder-LeftCollapse-trigger': string;
  'builder-LeftCollapse-trigger-wrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
