// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TabItem': string;
  'active': string;
  'closeBtn': string;
  'nav': string;
  'nav-link': string;
  'nav-tabs': string;
  'tabView': string;
}
declare const cssExports: CssExports;
export = cssExports;
